name: Release Words

on:
  push:
    tags:
      - word-v**

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Zip
        run: zip -r data data/

      - name: Release Words
        uses: softprops/action-gh-release@v1
        with:
          files: data.zip
