name: CI

on: ['push', "pull_request"]

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macOS-latest, ubuntu-latest]
        cabal: ["3.6.2.0"]
        ghc: ["9.2.2"]
    steps:
    - uses: actions/checkout@v3

    - uses: haskell/actions/setup@v2
      name: Setup Haskell Stack
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: ${{ matrix.cabal }}

    - name: Add ~/.cabal/bin to PATH
      run: echo "$HOME/.cabal/bin" >> $GITHUB_PATH
    
    - name: Build
      run: cabal build
      id: build

    - name: Test
      run: cabal test

    - name: Build artifact
      if: startsWith(github.ref, 'refs/tags')
      run: make artifact
      env:
        PATAT_TAG: ${{ steps.get_version.outputs.version }}

    - uses: actions/upload-artifact@v2
      if: startsWith(github.ref, 'refs/tags')
      with:
        path: artifacts/*
        name: artifacts

  release:
    name: Release
    needs: build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macOS-latest, ubuntu-latest]
        cabal: ["3.6.2.0"]
        ghc: ["9.2.2"]

    if: startsWith(github.ref, 'refs/tags')

    steps:
    - name: Get the version
      id: get_version
      run: 'echo ::set-output name=version::${GITHUB_REF#refs/tags/}'

    - uses: actions/download-artifact@v2
      with:
        name: artifacts

    - name: Upload Linux Asset
      uses: softprops/action-gh-release@v1
      with: ./BDC-${{ steps.get_version.outputs.version }}-linux-x86_64.tar.gz

    - name: Upload MacOS Asset
      uses: softprops/action-gh-release@v1
      with: ./BDC-${{ steps.get_version.outputs.version }}-darwin-x86_64.zip

    - name: Upload Windows Asset
      uses: softprops/action-gh-release@v1
      with: ./BDC-${{ steps.get_version.outputs.version }}-windows-x86_64.zip

